### ISSUE TITLE
Roadmap to beta

### ISSUE THREAD

**Issue by wipe2238** [rotators/parr#1]
- base
  - [ ] Recreate PEGTL exception handler example without exceptions
  - [ ] `Parser` -> `ParserBase`, `ParserTool` -> `Parser`
    For better-looking `Parser<SSL> ssl` :)
  - [ ] Forced `run::Analyze` when using other modes
    Only once per instance lifetime (use `ParserTool` to hold status?)
  - [ ] Verify if rule-switching works properly with `run::Analyze()`
  - ???
    - [ ] Simplify PEGTL functionality wrappers
      Use `Parser::RunMode` instead of named functions
      Keep named functions in `ParserTool` only

- ssl
  - [ ] random stuff
  - [int2ssl](https://github.com/sfall-team/int2ssl) output
    - Vanilla
      - [ ] [Fallout 1](https://github.com/rotators/ReDefine.Examples/tree/master/Games/Fallout1.Steam/Original)
      - [ ] [Fallout 2](https://github.com/rotators/ReDefine.Examples/tree/master/Games/Fallout2.Steam/Original)
    - Closed source
      - [ ] [DemoInFO2](https://github.com/rotators/ReDefine.Examples/tree/master/Mods/DemoInFO2/Original)
      - [ ] [Mutants Rising demo](https://github.com/rotators/ReDefine.Examples/tree/master/Mods/MutantsRising.demo/Original)
      - [ ] [MegaMod](https://github.com/rotators/ReDefine.Examples/tree/master/Mods/MegaMod/Original)
  - Vanilla
    - [ ] [Fallout 2](https://nma-fallout.com/resources/bis-mapper.55/)
  - Closed source leaks
    - [ ] [REDACTED]
  - Open source
    - sfall
      - [ ] [Examples](https://github.com/sfall-team/sfall/tree/master/artifacts/example_mods)
      - [ ] [Mods](https://github.com/sfall-team/sfall/tree/master/artifacts/mods)
    - [ ] [Unofficial Patch](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/tree/master/scripts_src)
    - [ ] [Mini-mods](https://github.com/rotators/fallout-mods)
    - [ ] [FO2Tweaks](https://github.com/BGforgeNet/FO2tweaks/tree/master/source)
    - [ ] [RPU](https://github.com/BGforgeNet/Fallout2_Restoration_Project/tree/master/scripts_src)
    - [ ] [EcCo](https://github.com/phobos2077/fo2_ecco/tree/master/scripts_src)
    - [ ] [FO1@2](https://github.com/rotators/Fo1in2/tree/master/Fallout2/Fallout1in2/Mapper/source/scripts)

- preprocessor
  - [ ] `#pragma` logic
  - [ ] `#define`
  - [ ] `#include`
  - [ ] `#if` / `#endif`
